import math
import sys
import io
import traceback
from fractions import Fraction
import sympy as sp


def execute_math_code(code: str) -> dict:
    """
    Safely executes Python math code generated by the LLM.
    Returns stdout output and any errors.
    """
    old_stdout = sys.stdout
    sys.stdout = buffer = io.StringIO()

    namespace = {
        # Math functions
        "math":      math,
        "comb":      math.comb,
        "perm":      math.perm,
        "factorial": math.factorial,
        "sqrt":      math.sqrt,
        "gcd":       math.gcd,
        "pi":        math.pi,
        "e":         math.e,
        "inf":       math.inf,
        "log":       math.log,
        "exp":       math.exp,
        "ceil":      math.ceil,
        "floor":     math.floor,
        "sin":       math.sin,
        "cos":       math.cos,
        "tan":       math.tan,
        # Fraction for exact results
        "Fraction":  Fraction,
        # Sympy for symbolic math
        "sp":        sp,
        "sympy":     sp,
        "symbols":   sp.symbols,
        "diff":      sp.diff,
        "integrate": sp.integrate,
        "solve":     sp.solve,
        "limit":     sp.limit,
        "simplify":  sp.simplify,
        "expand":    sp.expand,
        "factor":    sp.factor,
        "Abs":       sp.Abs,
        "ln":        sp.ln,
        "exp_sp":    sp.exp,
        "sqrt_sp":   sp.sqrt,
        "oo":        sp.oo,
        "pi_sp":     sp.pi,
        "Rational":  sp.Rational,
        "Matrix":    sp.Matrix,
        "det":       lambda m: sp.Matrix(m).det(),
        "eigenvals": lambda m: sp.Matrix(m).eigenvals(),
        # Python builtins
        "print":     print,
        "abs":       abs,
        "round":     round,
        "range":     range,
        "sum":       sum,
        "min":       min,
        "max":       max,
        "int":       int,
        "float":     float,
        "str":       str,
        "list":      list,
        "dict":      dict,
        "enumerate": enumerate,
        "zip":       zip,
        "len":       len,
        "sorted":    sorted,
        "True":      True,
        "False":     False,
        "None":      None,
    }

    
    try:
        exec(code, namespace)
        output = buffer.getvalue()
        return {
            "success": True,
            "output":  output.strip(),
            "error":   ""
        }
    except Exception:
        return {
            "success": False,
            "output":  "",
            "error":   traceback.format_exc()
        }
    finally:
        sys.stdout = old_stdout


if __name__ == "__main__":
    # Test 1: Committee problem
    test1 = """
total = comb(16, 12)
favorable = (comb(4,3)*comb(2,1)*comb(10,8) +
             comb(4,3)*comb(2,2)*comb(10,7) +
             comb(4,4)*comb(2,1)*comb(10,7) +
             comb(4,4)*comb(2,2)*comb(10,6))
prob = Fraction(favorable, total)
print(f"Total ways: {total}")
print(f"Favorable: {favorable}")
print(f"Probability: {prob}")
"""
    r1 = execute_math_code(test1)
    print("Test 1 - Committee Problem:")
    print(r1["output"] if r1["success"] else r1["error"])

    # Test 2: Quadratic roots
    test2 = """
a, b, c = 1, -5, 6
discriminant = b**2 - 4*a*c
r1 = (-b + sqrt(discriminant)) / (2*a)
r2 = (-b - sqrt(discriminant)) / (2*a)
print(f"Roots: {r1}, {r2}")
print(f"Sum of squares: {r1**2 + r2**2}")
"""
    r2 = execute_math_code(test2)
    print("\nTest 2 - Quadratic Roots:")
    print(r2["output"] if r2["success"] else r2["error"])

    # Test 3: Last digit probability
    test3 = """
prob = Fraction(4, 10)**4
print(f"Probability last digit in {{1,3,7,9}}: {prob}")
"""
    r3 = execute_math_code(test3)
    print("\nTest 3 - Last Digit Probability:")
    print(r3["output"] if r3["success"] else r3["error"])
